# Generated by Django 5.2.4 on 2025-08-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_reset_token_user_reset_token_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
